module.exports = {
    // Packet constants
    PLAYER_START: "1",
    PLAYER_ADD: "2",
    PLAYER_ANGLE: "2",
    PLAYER_UPDATE: "3",
    PLAYER_ATTACK :"4",
    LEADERBOAD: "5",
    PLAYER_MOVE: "3",
    PLAYER_REMOVE: "4",
    LEADERS_UPDATE: "5",
    LOAD_GAME_OBJ: "6",
    PLAYER_UPGRADE: "6",
    GATHER_ANIM: "7",
    AUTO_ATK: "7",
    WIGGLE: "8",
    CLAN_CREATE: "8",
    PLAYER_LEAVE_CLAN: "9",
    STAT_UPDATE: "9",
    CLAN_REQ_JOIN: "10",
    UPDATE_HEALTH: "10",
    CLAN_ACC_JOIN: "11",
    CLAN_KICK: "12",
    ITEM_BUY: "13",
    UPDATE_AGE: "15",
    UPGRADES: "16",
    CHAT: "ch",
    CLAN_DEL: "ad",
    PLAYER_SET_CLAN: "st",
    SET_CLAN_PLAYERS: "sa",
    CLAN_ADD: "ac",
    CLAN_NOTIFY: "an",
    MINIMAP: "mm",
    UPDATE_STORE: "us",
    DISCONN: "d"
}